services:
  mensatt-img:
    build:
      dockerfile: Dockerfile
    container_name: mensatt-img
    image: mensatt-img:latest
    volumes:
      - ./data/:/data
      - ./config.yml:/config.yml
    ports:
      - 3000:3000
    environment:
      # Values in ${} are automatically sourced from .env in current directory
      # Separated using ';'
      API_KEY_HASHES: ${API_KEY_HASHES:?} # :? ensures value is set and non-empty
      # To enable more verbose logging
      # RUST_LOG: "mensatt_img=debug"
